### ISSUE TITLE
OFDB.bundle for TV series libraries

### ISSUE THREAD

**Issue by rossinior** [plexinc-agents/OFDB.bundle#4]
Hey sander1,

I really like your OFDB scraper and use it as standard source for movie libraries within Plex.

I really hope that you can extend its reach also for TV series library types.

While I am unsure if pulling the summary for tv series is a good idea, you can easily pull FSK, genre, title, and ratings from OFDB - the same way you already do for movies.

For the titel, you would need to cut out " [TV-Serie]" at the end...

Such an extension would be very welcome for German based libraries. At the moment, I only get foreign ratings for series.

**Comment by sander1** [comment]
For movies the OFDB site provides a search method that takes the IMDb id (which we get from the primary Plex agent) as input. Such an option does not exist for TV series...

**Comment by rossinior** [comment]
OFDB.de search is also working with IMDB IDs for TV series...
Do you mean that the Primary plex Agent does not deliver an IMDB ID?

At least for TVDB, I found the following:

https://www.themoviedb.org/talk/5851f2ddc3a368258c0127b0?language=de
https://api.themoviedb.org/3/movie/550?api_key=###

While I understand that this is not possible atm, you contacts could make it work in a future version of the tvdb agent?

**Comment by rossinior** [comment]
If the api key is the problem, why not offering a field in the scraper's config dialog for that... :)

**Comment by sander1** [comment]
> If the api key is the problem, why not offering a field in the scraper's config dialog for that... :)

The api key is not the issue. The "problem" is that you have to convert the TVDB id into an IMDb id, and the only possible route at this moment (that I know of) is doing it through yet another site (TMDB):

```
Get tvdb id from primary agent
  --> tmdb: use /find endpoint to find tmdb id based on tvdb id
    --> tmdb: use /tv endpoint with tmdb id to get details and imdb id
      --> ofdb: do search with imdb id
```

**Comment by sander1** [comment]
> Just tried it with my own API key for Hell on Wheels, cheanging the TVDB ID in the second link above, I got the following output

Sorry, I don't quite follow this. The TVDB ID for "Hell in Wheels" is `212961`. You can't just add that id into the Movie Database URL like so: `https://api.themoviedb.org/3/movie/212961?api_key=###`

Well, you can, but as you can see you get data about a very different item (a Disney movie in this case).

**Comment by rossinior** [comment]
Yes, you are correct....

Here is the documentation of that with v2 of the API

https://api.thetvdb.com/swagger#!/Series/head_series_id

**Comment by rossinior** [comment]
https://api.thetvdb.com/swagger#!/Series/get_series_id

**Comment by sander1** [comment]
@piplongrun wrote me a nice, tiny API to make it very easy to retrieve an IMDb ID from a TVDB ID (Example: https://api.tadata.me/tvdb2imdb/v1/?tvdb_id=275274). I'm going to integrate this into OFDD.

**Comment by sander1** [comment]
Done! The updated agent has been released!
