### ISSUE TITLE
TV Series... non-German TVDB entries available, connection to OFDB not done

### ISSUE THREAD

**Issue by rossinior** [plexinc-agents/OFDB.bundle#6]
For TV series, which are existant in TVDB in English, but not in German, the connection for OFDB is not done though the ID would be the same and OFDB would have German descriptions.

Examples for such TV series:

Masada
https://ssl.ofdb.de/film/11138,Masada

Yes Minister
https://ssl.ofdb.de/film/45166,Yes-Minister

I have no ID if OFDB holds no TVDB IDs for these series or if the OFDB plugin only likes the TV series if  there is a German TVDB page for it or if the TVDB agent in Plex does not transport the ID (but the non-German content).

**Comment by sander1** [comment]
If the primary agent (TVDB) does not find a match, the secondary agents (like OFDB) aren't called. That is standard behaviour and can't be fixed inside the OFDB agent.

**Comment by sander1** [comment]
I removed a language check from the last version, you should now be able to fix a match like this:

- Op the `Fix Match...` menu.
- Click `Search Options`.
- Lookup the TVDB id and enter it into the `Title` field.
- Change language to `English` and press `Search`.

![screen shot 2017-08-23 at 00 06 25](https://user-images.githubusercontent.com/104684/29589929-b85f0332-8797-11e7-932d-735b83187f4d.jpg)
