### ISSUE TITLE
Few German TV shows do not get OFDB data

### ISSUE THREAD

**Issue by rossinior** [plexinc-agents/OFDB.bundle#7]
The ODFB TV show feature works good, with a few execptions.
No matter how hard I try, the transition from TVDB ID to IMDB ID does not work for the following shows:

A) Das Juwel der Krone / The Jewel in the Crown (1984):

https://api.tadata.me/tvdb2imdb/v1/?tvdb_id=71353
returns:
{"error":"Could not find IMDb id.","code":"8006","generated":"Sun, 10 Sep 2017 22:02:42 +0200"}

Although the TVDB ID is registered correctly with the show's web page at TVDB.com:
https://www.thetvdb.com/?tab=series&id=71353&lid=7

B) Lazy company (2013):

https://www.thetvdb.com/?tab=series&id=264961&lid=14
contains the IMDB ID...
https://api.tadata.me/tvdb2imdb/v1/?tvdb_id=264961
generates...
{"error":"Could not find IMDb id.","code":"8006","generated":"Sun, 10 Sep 2017 22:08:04 +0200"}

C) Goldene Zeiten - Bittere Zeiten (1981):

https://www.thetvdb.com/?tab=series&id=291538&lid=14
contains the following IMDB ID: tt0169434 (which is correct).
But the API ...
https://api.tadata.me/tvdb2imdb/v1/?tvdb_id=291538
generates...
{"series":null,"imdb_id":"tt0168441","generated":"Sun, 10 Sep 2017 22:10:25 +0200"}
Which is the wrong IMDB ID...

Is there any renewal process at api.tadata.me for that?

**Comment by sander1** [comment]
My backend cache is approximately 7 days to lower the load on their API server(s). The pieces of data I use most hardly change, that's why it takes some time before changes made on the TVDB site show up on api.tadata.me. Above three examples should work by now as I've manually refreshed the data.

**Comment by rossinior** [comment]
Oh, thank you. You are right about caching. Did not think of that. It shouldn't do caching on "no IMDB ID found" though...

**Comment by sander1** [comment]
> It shouldn't do caching on "no IMDB ID found" though...

Unfortunately that's not possible, because at cache level it's not possible to tell what pieces of data are present or missing. As long as the request comes back as 200 OK it's cached.
